Repository Rapiders/react-hooks, pull requests merged in 2024-05, with the labels that each got.

#4 feat: rollup-terser 적용하여 번들 사이즈 줄이기 처리
  package-lock.json
  package.json
  rollup.config.js
Labels: enhancement

#5 feat: useInterval 반환 상태 추가 & stroybook 추가
  README.md
  src/stories/useInterval/Docs.mdx
  src/stories/useInterval/Interval.stories.ts
  src/stories/useInterval/Interval.tsx
  src/useInterval/useInterval.ts
Labels: enhancement, feature

#6 feat: useAfterMountEffect 훅 추가
  README.md
  package-lock.json
  src/index.ts
  src/useAfterMountEffect/useAfterMountEffect.test.tsx
  src/useAfterMountEffect/useAfterMountEffect.ts
Labels: feature

#7 config: CI구성, useDragIndexCarousel 테스트 깨지는 문제 해결
  .github/workflows/CI.yml
  package-lock.json
  package.json
  src/useDragIndexCarousel/useDragIndexCarousel.test.tsx
  src/useDragIndexCarousel/useDragIndexCarousel.tsx
Labels: fix, enhancement

#8 feat: eslint, prettier, husky 적용
  .eslintrc.cjs
  .gitignore
  .husky/pre-commit
  .prettierrc
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  rollup.config.js
  src/index.ts
  src/stories/useAnimation/Animation.tsx
  src/stories/useAnimation/animation.css
  src/stories/useCarousel/Carousel.tsx
  src/stories/useDragIndexCarousel/DragCarousel.tsx
  src/stories/useDragIndexCarousel/TimerDragCarousel.stories.ts
  src/stories/useDragIndexCarousel/TimerDragCarousel.tsx
  src/stories/useFocusAnimation/FocusAnimation.tsx
  src/stories/useInterval/Interval.tsx
  src/useAnimation/_useAnimation.test.ts
  src/useAnimation/useAnimation.test.tsx
  src/useAnimation/useAnimation.tsx
  src/useCarousel/useCarousel.test.tsx
  src/useCarousel/useCarousel.tsx
  src/useDragIndexCarousel/useDragIndexCarousel.test.tsx
  src/useDragIndexCarousel/useDragIndexCarousel.tsx
  src/useFocusAnimation/useFocusAnimation.test.tsx
  src/useFocusAnimation/useFocusAnimation.ts
  src/useInput/useInput.ts
  tsconfig.json
Labels: enhancement

#9 feat: useRadio 훅 추가
  README.md
  src/stories/useRadio/Docs.mdx
  src/stories/useRadio/Radio.stories.ts
  src/stories/useRadio/Radio.tsx
  src/useRadio/useRadio.test.tsx
  src/useRadio/useRadio.tsx
Labels: feature

#10 feat: eslint 캐시 설정 및 lint-staged jest 적용
  .gitignore
  .husky/pre-commit
  package.json
Labels: feature

#11 config: docs 사이트 GA설치
  .storybook/main.ts
Labels: enhancement

#17 feat: storybook vanilla extract 적용
  .storybook/global.css
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/stories/useAnimation/Animation.css.ts
  src/stories/useAnimation/Animation.stories.ts
  src/stories/useAnimation/Animation.tsx
  src/stories/useCarousel/Carousel.css.ts
  src/stories/useCarousel/Carousel.tsx
  src/stories/useDragIndexCarousel/DragCarousel.css.ts
  src/stories/useDragIndexCarousel/DragCarousel.tsx
  src/stories/useDragIndexCarousel/TimerDragCarousel.tsx
  src/stories/useFocusAnimation/FocusAnimation.css.ts
  src/stories/useFocusAnimation/FocusAnimation.tsx
  src/stories/useFocusAnimation/focusAnimation.css
  src/stories/useInput/Input.css.ts
  src/stories/useInput/Input.tsx
  src/stories/useInput/input.css
  src/stories/useInterval/Interval.tsx
  src/stories/useRadio/Radio.tsx
  src/useAnimation/useAnimation.tsx
  tsconfig.json
Labels: documentation, enhancement

#16 feat: useDebounce, useThrottle 훅 기능 추가
  README.md
  src/index.ts
  src/stories/useDebounce/Debounce.css.ts
  src/stories/useDebounce/Debounce.stories.ts
  src/stories/useDebounce/Debounce.tsx
  src/stories/useDebounce/Docs.mdx
  src/stories/useThrottle/Docs.mdx
  src/stories/useThrottle/Throttle.css.ts
  src/stories/useThrottle/Throttle.stories.ts
  src/stories/useThrottle/Throttle.tsx
  src/useDebounce/useDebounce.test.ts
  src/useDebounce/useDebounce.ts
  src/useThrottle/useThrottle.test.ts
  src/useThrottle/useThrottle.ts
Labels: feature

#18 feat: useLocalStorage 추가
  README.md
  package.json
  src/index.ts
  src/useLocalStorage/useLocalStorage.test.ts
  src/useLocalStorage/useLocalStorage.ts
  src/utils/isServer.test.ts
  src/utils/isServer.ts
Labels: feature

#19 docs: useLocalStorage 스토리북 작성
  package.json
  src/stories/useLocalStorage/Docs.mdx
  src/stories/useLocalStorage/LocalStorage.css.ts
  src/stories/useLocalStorage/LocalStorage.stories.ts
  src/stories/useLocalStorage/LocalStorage.tsx
Labels: documentation

#20 feat: develop useSwitch custom hook
  src/stories/useSwitch/Docs.mdx
  src/stories/useSwitch/Switch.css
  src/stories/useSwitch/Switch.stories.ts
  src/stories/useSwitch/Switch.tsx
  src/useBoolean/_useBoolean.test.ts
  src/useBoolean/useBoolean.ts
  src/useSwitch/_useSwitch.test.ts
  src/useSwitch/useSwitch.ts
Labels: feature
